In [71]:
import pandas as pd
import numpy as np

In [72]:
deal = pd.read_excel('reg_deals.xlsx')
deal.head()

,Номер мультизаявки,ИНН,Заявка,Текущий статус,Причина отмены,Дата создания,Дата окончания сделки,Категория,Федеральный округ,Область / Край /Республика,Оплата прошла,Item Type
0,NaN,641802234254,Агросервисы,Завершена,NaN,2021-10-04,2021-10-13,NaN,ПФО,Саратовская область,Да,Элемент
1,NaN,9105015900,Агросервисы,Завершена,NaN,2021-10-30,2021-10-13,NaN,ЮФО,Республика Крым,Да,Элемент
2,NaN,9704075070,Агросервисы,Завершена,NaN,2021-08-26,2021-10-13,NaN,ЦФО,г. Москва,Да,Элемент
3,NaN,460702516927,Агросервисы,Завершена,NaN,2021-10-26,2021-10-27,NaN,ЦФО,Курская область,Да,Элемент
4,NaN,5252015340,Агросервисы,Завершена,NaN,2021-11-16,2021-11-21,NaN,ПФО,Нижегородская область,Да,Элемент

In [73]:
deal.describe(include='all')

C:\Users\KVV_1\AppData\Local\Temp\ipykernel_35636\1234915847.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  deal.describe(include='all')
C:\Users\KVV_1\AppData\Local\Temp\ipykernel_35636\1234915847.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  deal.describe(include='all')

,Номер мультизаявки,ИНН,Заявка,Текущий статус,Причина отмены,Дата создания,Дата окончания сделки,Категория,Федеральный округ,Область / Край /Республика,Оплата прошла,Item Type
count,565,3313,3313,3313,2983,3313,3106,1129,3313,3313,1074,3313
unique,116,2021,6,19,46,251,203,30,8,90,2,1
top,M19,262505015969,Финансирование,Отменена партнером,Фермер не обозначил реальную причину,2022-04-06 00:00:00,2021-11-30 00:00:00,Пшеница,ЦФО,Краснодарский край,Нет,Элемент
freq,6,40,2248,1282,645,57,247,388,902,304,962,3313
first,NaN,NaN,NaN,NaN,NaN,2021-06-22 00:00:00,2021-07-29 00:00:00,NaN,NaN,NaN,NaN,NaN
last,NaN,NaN,NaN,NaN,NaN,2022-05-15 00:00:00,2022-05-14 00:00:00,NaN,NaN,NaN,NaN,NaN

In [74]:
deal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3313 entries, 0 to 3312
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Номер мультизаявки          565 non-null    object
 1   ИНН                         3313 non-null   object
 2   Заявка                      3313 non-null   object
 3   Текущий статус              3313 non-null   object
 4   Причина отмены              2983 non-null   object
 5   Дата создания               3313 non-null   datetime64[ns]
 6   Дата окончания сделки       3106 non-null   datetime64[ns]
 7   Категория                   1129 non-null   object
 8   Федеральный округ           3313 non-null   object
 9   Область / Край /Республика  3313 non-null   object
 10  Оплата прошла               1074 non-null   object
 11  Item Type                   3313 non-null   object
dtypes: datetime64[ns](2), object(10)
memory usage: 310.7+ KB

In [75]:
deal['Заявка'].value_counts()

Финансирование                  2248
Продажа урожая                   737
Сельхозтовары                    235
Агросервисы                       89
Агросервисы​                       3
Агросервисы                        1
Name: Заявка, dtype: int64

In [76]:
deal['Текущий статус'].value_counts()

Отменена партнером                        1282
Отменена фермером                          974
Мультизаявка_отменена партнером            249
Отменена Админом                           196
Мультизаявка_отменена админом              168
Завершена                                  113
SENT                                        94
Активная                                    64
Мультизаявка_отменена автоматически         45
Мультизаявка_отменена фермером              44
Мультизаявка                                38
Отменена КЦ                                 24
Мультизаявка_активная                        8
LJqrb?PV5KD3"*c#                             7
Завершена​                                   2
Проверена КЦ на минимальные требования       2
Отменена Админом​                            1
Холд                                         1
Завершена 1я отгрузка                        1
Name: Текущий статус, dtype: int64

In [77]:
deal[deal['Текущий статус'] == 'LJqrb?PV5KD3"*c#']

,Номер мультизаявки,ИНН,Заявка,Текущий статус,Причина отмены,Дата создания,Дата окончания сделки,Категория,Федеральный округ,Область / Край /Республика,Оплата прошла,Item Type
8,NaN,2258004934,Агросервисы,"LJqrb?PV5KD3""*c#",NaN,2021-11-29,2021-11-28,NaN,СФО,Алтайский край,Да,Элемент
24,NaN,2247004890,Агросервисы​,"LJqrb?PV5KD3""*c#",NaN,2021-12-28,2022-01-21,NaN,СФО,Алтайский край,Да,Элемент
37,NaN,2221226560,Агросервисы​,"LJqrb?PV5KD3""*c#",NaN,2022-02-08,2022-02-15,NaN,СФО,Алтайский край,Да,Элемент
39,NaN,228001115705,Агросервисы​,"LJqrb?PV5KD3""*c#",NaN,2022-02-14,2022-02-15,NaN,СФО,Алтайский край,Да,Элемент
45,NaN,2287006573,Агросервисы,"LJqrb?PV5KD3""*c#",NaN,2022-02-14,2022-02-16,NaN,СФО,Алтайский край,Да,Элемент
65,NaN,228601261553,Агросервисы,"LJqrb?PV5KD3""*c#",NaN,2022-04-11,2022-04-18,NaN,СФО,Алтайский край,Да,Элемент
1326,NaN,225802946618,Финансирование,"LJqrb?PV5KD3""*c#",NaN,2022-01-19,2022-01-20,NaN,СФО,Алтайский край,NaN,Элемент

In [78]:
deal['Текущий статус'] = deal['Текущий статус'].replace(['LJqrb?PV5KD3"*c#'], 'другое')

In [79]:
deal['Текущий статус'].value_counts()

Отменена партнером                        1282
Отменена фермером                          974
Мультизаявка_отменена партнером            249
Отменена Админом                           196
Мультизаявка_отменена админом              168
Завершена                                  113
SENT                                        94
Активная                                    64
Мультизаявка_отменена автоматически         45
Мультизаявка_отменена фермером              44
Мультизаявка                                38
Отменена КЦ                                 24
Мультизаявка_активная                        8
другое                                       7
Завершена​                                   2
Проверена КЦ на минимальные требования       2
Отменена Админом​                            1
Холд                                         1
Завершена 1я отгрузка                        1
Name: Текущий статус, dtype: int64

In [80]:
deal['ИНН'].describe()

count             3313
unique            2021
top       262505015969
freq                40
Name: ИНН, dtype: object

In [81]:
deal['ИНН'].astype(int)

OverflowError: Python int too large to convert to C long

In [82]:
def check_int(value):
	try:
		int(value)
		return np.NaN
	except ValueError:
		return value

In [83]:
deal.ИНН.apply(check_int).dropna()

163       1650310080<br>
167       5824002830<br>
172       6727037491<br>
173       6727037491<br>
197       7703704469<br>
198       7703704469<br>
1902    234800631582<br>
1904      5824002830<br>
1919    742801019315<br>
2331      5248012924<br>
2332      4618003185<br>
2333      4618003185<br>
2915      5260467830<br>
Name: ИНН, dtype: object

In [84]:
deal.ИНН = deal.ИНН.str.replace(r'\D+', '', regex=True)

In [85]:
deal.ИНН.apply(check_int).dropna()

Series([], Name: ИНН, dtype: float64)

In [86]:
deal['Причина отмены'].describe()

count                                     2983
unique                                      46
top       Фермер не обозначил реальную причину
freq                                       645
Name: Причина отмены, dtype: object

In [87]:
deal['Причина отмены'].value_counts()

Фермер не обозначил реальную причину                     645
Окончательный недозвон                                   394
Отказ партнера                                           328
Не произошло конвертации в лид                           210
Пробная/измененная заявка                                190
Не устроило ценовое предложение                          177
Неактуально для фермера                                  175
Не пройдена проверка                                     160
Закупщик не закупает культуру                            120
Временно не закупают в регионе                            83
Нет нужного сервиса / услуги                              69
Нарушение SLA со стороны партнера                         52
Автоотмена                                                44
Товара на текущий момент нет в наличии у поставщика       43
Нарушение SLA со стороны фермера                          40
Продал в другом месте                                     36
Закупил в другом месте                                    31
Партнер не готов указать цену на товар                    26
Изменилась желаемая дата продажи/приобретения             23
Нет отделения в городе                                    15
Не устроило качество товара                               13
Невозможен забор из региона поставки                      11
Клиент отрицает факт заполнения заявки                     9
Нет возможности оплатить заказ на текущий момент           8
Не устраивает объем                                        7
Товара нет в ассортименте у поставщика                     7
Не устроила цена на логистику                              7
Нет дистанционного оформления                              7
Не устроило предложение                                    6
Оформил продукт в другом банке                             6
Квота: запрос в другой регион                              6
Квота: фермер-перекуп                                      6
Не устраивают сроки оформления                             5
Невозможен базис поставки, который интересует клиента      4
Нет нужного сервиса/услуги                                 3
Не устраивает пакет документов на аккредитацию             3
Не устроила логистика                                      2
Сомнения в надежности партнера                             2
Недостаточность функционала на МП                          2
Не удобен/не понятен функционал МП                         2
Сомнения в надежности МП                                   1
Интересовала только цена                                   1
Фермер не готов приобрести услугу после КП                 1
Закрытый экспорт                                           1
Неактуален частичный выкуп                                 1
Квота: достижение квоты в регионе                          1
Name: Причина отмены, dtype: int64

In [88]:
deal['Причина отмены'].isna().count()

3313

In [89]:
deal['Категория'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 3313 entries, 0 to 3312
Series name: Категория
Non-Null Count  Dtype
--------------  -----
1129 non-null   object
dtypes: object(1)
memory usage: 26.0+ KB

In [90]:
deal['Категория'].value_counts()

Пшеница                                                                                                                                                                                                                                                                                                                                                                388
Подсолнечник масличный                                                                                                                                                                                                                                                                                                                                                 130
Кукуруза                                                                                                                                                                                                                                                                                                                                                               120
Удобрения                                                                                                                                                                                                                                                                                                                                                               92
Средства защиты растений                                                                                                                                                                                                                                                                                                                                                61
Ячмень                                                                                                                                                                                                                                                                                                                                                                  60
Тинькофф                                                                                                                                                                                                                                                                                                                                                                59
Семена различных культур                                                                                                                                                                                                                                                                                                                                                39
Соя                                                                                                                                                                                                                                                                                                                                                                     32
Лизинг                                                                                                                                                                                                                                                                                                                                                                  30
`54WVhT"J3wxhdkm                                                                                                                                                                                                                                                                                                                                                        25
Кредиты                                                                                                                                                                                                                                                                                                                                                                 17
Авансирование                                                                                                                                                                                                                                                                                                                                                           16
Азотные                                                                                                                                                                                                                                                                                                                                                                 12
Экспресс-кредит онлайн                                                                                                                                                                                                                                                                                                                                                   6
Гербициды                                                                                                                                                                                                                                                                                                                                                                6
Сельхозтехника                                                                                                                                                                                                                                                                                                                                                           6
Рапс                                                                                                                                                                                                                                                                                                                                                                     5
Горюче-смазочные материалы                                                                                                                                                                                                                                                                                                                                               5
Комплексные                                                                                                                                                                                                                                                                                                                                                              3
Инсектициды                                                                                                                                                                                                                                                                                                                                                              3
Фунгициды                                                                                                                                                                                                                                                                                                                                                                3
Лизинг автотранспорта и спецтехники                                                                                                                                                                                                                                                                                                                                      3
Подсолнечник кондитерский                                                                                                                                                                                                                                                                                                                                                2
Запасные части                                                                                                                                                                                                                                                                                                                                                           1
Запчасти для сельхозмашин                                                                                                                                                                                                                                                                                                                                                1
Микроудобрения                                                                                                                                                                                                                                                                                                                                                           1
Фосфорно-калийные                                                                                                                                                                                                                                                                                                                                                        1
data.capital\tУставной капитал компании\n└ type\t— тип капитала\n└ value\t— размер капитала\ndata.finance\tФинансовые показатели за год\nчастично заполнены у 70% действующих компаний\n└ year\t— год бух. отчетности\n└ income\t— доходы по бух. отчетности\n└ expense\t— расходы по бух. отчетности\n└ debt\t— недоимки по налогам\n└ penalty\t— налоговые штрафы      1
Опрыскиватели                                                                                                                                                                                                                                                                                                                                                            1
Name: Категория, dtype: int64

In [91]:
deal[deal['Категория'] == '`54WVhT"J3wxhdkm']

,Номер мультизаявки,ИНН,Заявка,Текущий статус,Причина отмены,Дата создания,Дата окончания сделки,Категория,Федеральный округ,Область / Край /Республика,Оплата прошла,Item Type
1901,NaN,461800197340,Финансирование,Активная,NaN,2021-10-06,NaT,"`54WVhT""J3wxhdkm",ЦФО,Курская область,NaN,Элемент
1904,NaN,5824002830,Финансирование,Активная,NaN,2021-10-14,NaT,"`54WVhT""J3wxhdkm",ПФО,Пензенская область,NaN,Элемент
1912,NaN,081406926204,Финансирование,Активная,NaN,2021-10-19,NaT,"`54WVhT""J3wxhdkm",ЮФО,Республика Калмыкия,NaN,Элемент
1913,NaN,023201556318,Финансирование,Активная,NaN,2021-10-19,NaT,"`54WVhT""J3wxhdkm",ПФО,Республика Башкортостан,NaN,Элемент
1919,NaN,742801019315,Финансирование,Активная,NaN,2021-10-21,NaT,"`54WVhT""J3wxhdkm",УФО,Челябинская область,NaN,Элемент
1928,NaN,060102798108,Финансирование,Активная,NaN,2021-10-22,NaT,"`54WVhT""J3wxhdkm",СКФО,Республика Ингушетия,NaN,Элемент
1930,NaN,261902112406,Финансирование,Активная,NaN,2021-10-23,NaT,"`54WVhT""J3wxhdkm",СКФО,Ставропольский край,NaN,Элемент
1935,NaN,245011369199,Финансирование,Активная,NaN,2021-10-26,NaT,"`54WVhT""J3wxhdkm",СФО,Красноярский край,NaN,Элемент
1938,NaN,90107441894,Финансирование,Активная,NaN,2021-10-27,NaT,"`54WVhT""J3wxhdkm",СКФО,Карачаево-Черкесская Республика,NaN,Элемент
1940,NaN,570300863454,Финансирование,Активная,NaN,2021-10-28,NaT,"`54WVhT""J3wxhdkm",ЦФО,Орловская область,NaN,Элемент
1946,NaN,235404863510,Финансирование,Активная,NaN,2021-10-30,NaT,"`54WVhT""J3wxhdkm",ЮФО,Краснодарский край,NaN,Элемент
1948,NaN,6140031289,Финансирование,Активная,NaN,2021-11-01,NaT,"`54WVhT""J3wxhdkm",ЮФО,Ростовская область,NaN,Элемент
1949,NaN,371600160963,Финансирование,Активная,NaN,2021-11-02,NaT,"`54WVhT""J3wxhdkm",ЦФО,Ивановская область,NaN,Элемент
1976,NaN,542905485259,Финансирование,Активная,NaN,2021-11-14,NaT,"`54WVhT""J3wxhdkm",СФО,Новосибирская область,NaN,Элемент
1980,NaN,6234143510,Финансирование,Активная,NaN,2021-11-15,NaT,"`54WVhT""J3wxhdkm",ЦФО,Рязанская область,NaN,Элемент
1988,NaN,5530005388,Финансирование,Активная,NaN,2021-11-17,NaT,"`54WVhT""J3wxhdkm",СФО,Омская область,NaN,Элемент
1991,NaN,2624801118,Финансирование,Активная,NaN,2021-11-19,NaT,"`54WVhT""J3wxhdkm",СКФО,Ставропольский край,NaN,Элемент
1992,NaN,7226004306,Финансирование,Активная,NaN,2021-11-19,NaT,"`54WVhT""J3wxhdkm",УФО,Тюменская область,NaN,Элемент
1997,NaN,202800401339,Финансирование,Активная,NaN,2021-11-23,NaT,"`54WVhT""J3wxhdkm",СКФО,Чеченская Республика,NaN,Элемент
2002,NaN,7329033549,Финансирование,Активная,NaN,2021-11-25,NaT,"`54WVhT""J3wxhdkm",ПФО,Ульяновская область,NaN,Элемент
2003,NaN,230111108928,Финансирование,Активная,NaN,2021-11-24,NaT,"`54WVhT""J3wxhdkm",ЮФО,Краснодарский край,NaN,Элемент
2024,NaN,342910427070,Финансирование,Активная,NaN,2021-11-30,NaT,"`54WVhT""J3wxhdkm",ЮФО,Волгоградская область,NaN,Элемент
2041,NaN,233905265490,Финансирование,Активная,NaN,2021-12-05,NaT,"`54WVhT""J3wxhdkm",ЮФО,Краснодарский край,NaN,Элемент
2056,NaN,680800030393,Финансирование,Активная,NaN,2021-12-08,NaT,"`54WVhT""J3wxhdkm",ЦФО,Тамбовская область,NaN,Элемент
2065,NaN,712808109329,Финансирование,Активная,NaN,2021-12-14,NaT,"`54WVhT""J3wxhdkm",ЦФО,Тульская область,NaN,Элемент

In [92]:
deal['Категория'] = deal['Категория'].replace(['`54WVhT"J3wxhdkm'], 'другое')

In [93]:
deal[deal['Категория'] == 'data.capital\tУставной капитал компании\n└ type\t— тип капитала\n└ value\t— размер капитала\ndata.finance\tФинансовые показатели за год\nчастично заполнены у 70% действующих компаний\n└ year\t— год бух. отчетности\n└ income\t— доходы по бух. отчетности\n└ expense\t— расходы по бух. отчетности\n└ debt\t— недоимки по налогам\n└ penalty\t— налоговые штрафы']

,Номер мультизаявки,ИНН,Заявка,Текущий статус,Причина отмены,Дата создания,Дата окончания сделки,Категория,Федеральный округ,Область / Край /Республика,Оплата прошла,Item Type
1687,NaN,1651079725,Финансирование,SENT,NaN,2021-11-01,NaT,data.capital\tУставной капитал компании\n└ typ...,ПФО,Республика Татарстан (Татарстан),NaN,Элемент

In [94]:
deal[deal['ИНН'] == '1651079725']

,Номер мультизаявки,ИНН,Заявка,Текущий статус,Причина отмены,Дата создания,Дата окончания сделки,Категория,Федеральный округ,Область / Край /Республика,Оплата прошла,Item Type
1687,NaN,1651079725,Финансирование,SENT,NaN,2021-11-01,NaT,data.capital\tУставной капитал компании\n└ typ...,ПФО,Республика Татарстан (Татарстан),NaN,Элемент

In [95]:
deal = deal.drop(deal[deal['ИНН'] == '1651079725'].index)

In [96]:
deal[deal['ИНН'] == '1651079725']

Empty DataFrame
Columns: [Номер мультизаявки, ИНН, Заявка, Текущий статус, Причина отмены, Дата создания, Дата окончания сделки, Категория, Федеральный округ, Область / Край /Республика, Оплата прошла, Item Type]
Index: []

In [97]:
deal['Федеральный округ'].value_counts()

ЦФО     902
ЮФО     642
СКФО    512
ПФО     456
СФО     295
ДФО     194
УФО     176
СЗФО    135
Name: Федеральный округ, dtype: int64

In [98]:
deal['Область / Край /Республика'].value_counts()

Краснодарский край                                     304
Воронежская область                                    241
Ставропольский край                                    240
г. Москва                                              189
Волгоградская область                                  140
                                                      ...
Саха (Якутия)                                            2
Удмуртская республика                                    2
Чувашская республика - Чувашия                           2
Севастополь                                              1
Иные территории, включая город и космодром Байконур      1
Name: Область / Край /Республика, Length: 90, dtype: int64

In [99]:
deal['Оплата прошла'].value_counts()

Нет    962
Да     112
Name: Оплата прошла, dtype: int64

In [100]:
deal['Item Type'].value_counts()

Элемент    3312
Name: Item Type, dtype: int64

In [101]:
deal.shape

(3312, 12)

In [102]:
# Поскольку у меня не получилось руками поменять тип поля в DataLens с числа на строку, чтобы связать с inn в таблице _organizations (я ее не чистил, и там есть строковые значения),
# пришлось добавить эту строку, чтобы обмануть Datalens

deal = deal.append({'ИНН': 'empty string'}, ignore_index=True)

C:\Users\KVV_1\AppData\Local\Temp\ipykernel_35636\3663018632.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  deal = deal.append({'ИНН': 'empty string'}, ignore_index=True)

In [103]:
deal.shape

(3313, 12)

In [104]:
deal.to_csv('reg_deals.csv', index=False)